[package]
name = "sgf-render"
version = "1.3.1"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["baduk", "sgf", "go", "svg", "png"]
repository = "https://github.com/julianandrews/sgf-render/"
readme = "README.md"
description = "A renderer for SGF diagrams."
categories = ["command-line-utilities", "multimedia::images", "rendering", "visualization"]

[features]
default = ["png"]
png = ["resvg", "usvg"]

[dependencies]
getopts = "0.2.21"
sgf-parse = "2.0.2"
svg = "0.8.0"

resvg = { version = "0.12.0", features = ["text"], optional = true }
usvg = { version = "0.12.0", optional = true }
